// Generated by CoffeeScript 1.7.1

/*
    Application class
    Having all viewControllers used in the application.
    This class instance can be accessed via window.system.app.
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app/controller/MapViewController', 'app/controller/DrawViewController', 'app/controller/RemarkViewController', 'app/controller/FeatureFormViewController', 'app/EventObserver', 'app/Module'], function(MapViewController, DrawViewController, RemarkViewController, FeatureFormViewController, EventObserver, Module) {
    var AppDelegate;
    return AppDelegate = (function(_super) {
      __extends(AppDelegate, _super);

      AppDelegate.prototype.drawViewController = null;

      AppDelegate.prototype.remarkViewController = null;

      AppDelegate.prototype.mapViewController = null;

      AppDelegate.prototype.featureFormViewController = null;

      AppDelegate.prototype.eventObserver = null;

      function AppDelegate(roles, initBbox) {
        var map;
        this.eventObserver = EventObserver.getInstance();
        this.mapViewController = new MapViewController('map', {
          initBbox: initBbox,
          maxZoom: 18,
          roles: roles
        });
        map = this.mapViewController.map;
        if ($.inArray(ROLE_USER, roles) !== -1) {
          this.drawViewController = new DrawViewController(map);
          this.featureFormViewController = new FeatureFormViewController(map, 'featureFormViewSidebar');
        }
        this.remarkViewController = new RemarkViewController(map, 'remarkViewSidebar');
      }

      AppDelegate.prototype.showFeatureFormView = function(isEditable) {
        var _ref;
        return (_ref = this.featureFormViewController) != null ? _ref.showViewControl() : void 0;
      };

      AppDelegate.prototype.showRemarkView = function() {
        var _ref;
        return (_ref = this.remarkViewController) != null ? _ref.showViewControl() : void 0;
      };

      return AppDelegate;

    })(Module);
  });

}).call(this);

//# sourceMappingURL=AppDelegate.map
