// Generated by CoffeeScript 1.7.1
(function () {
    define([], function () {
        var Events;
        return Events = (function () {
            function Events() {
            }

            Events.SET_BBOX = {
                name: 'SET_BBOX',
                description: 'used at FeatureFormView'
            };

            Events.REMOVE_LAYER = {
                name: 'REMOVE_LAYER',
                description: 'used at MapView'
            };

            Events.SET_GEOJSON = {
                name: 'SET_GEOJSON',
                description: 'used at FeatureFormView'
            };

            return Events;

        })();
    });

}).call(this);

//# sourceMappingURL=Events.map
