// Generated by CoffeeScript 1.7.1

/*
 A Notification is displayed at left top corner of screen, information of the notification
 is passed to client via a jsp model at page loading.
 */

(function () {
    define(['leaflet', 'jquery'], function (L, $) {
        var NotificationControl;
        NotificationControl = L.Control.extend;
        return {
            options: {
                position: 'topleft'
            },
            onAdd: function (map) {
                var container;
                container = L.DomUtil.create('div', 'notification-control');
                $("<div>" + window.system.notification + "&NonBreakingSpace;<a href='/'>[Top Page]</a></div>").appendTo(container);
                return container;
            }
        };
    });

}).call(this);

//# sourceMappingURL=NotificationControl.map
